/* ──────────────────────────────────────────────────────────────────────────
 * config.js — application configuration. please edit to add scenes / methods.
 *
 * The static CONFIG object holds playback constants and defaults.
 * Dataset/exposure/scene/method structure is loaded at runtime from
 * ./videos/manifest.json (generated by encode.py).
 *
 * Per-section knobs live under CONFIG.sections[sectionId]:
 *   - fps            playback fps assigned when this section becomes active.
 *   - sceneOrder     "hot-list" of scenes that should appear FIRST (in this
 *                    order); any scenes not in the list are appended after,
 *                    sorted alphabetically. Useful for pinning a few
 *                    showcase scenes to the front while still showing every
 *                    other encoded scene.
 *
 * Top-level CONFIG.showSceneNames toggles the textual scene label under
 * each thumbnail card. Disable for the polished view; re-enable while
 * debugging so the random-looking scene IDs are still visible.
 * ────────────────────────────────────────────────────────────────────────── */

window.App = window.App || {};

window.App.config = (function () {
  'use strict';

  const CONFIG = {

    // ── encode / playback parameters ─────────────────────────────────────
    fps:           24,      // fallback playback FPS if a section doesn't
                            // override it. Must match encoder --fps.
    frameCount:    17,      // frames per video.
    videoExtension: '.mp4', // container extension.

    // ── thumbnail / scene label visibility ───────────────────────────────
    // Most scene names are auto-generated and not pretty (e.g.
    // 'lediff_20250615_211644'). Hide labels for the published view;
    // flip back to true while developing so the IDs stay visible.
    showSceneNames: false,
    // showSceneNames: true,

    // ── default tone mapper ──────────────────────────────────────────────
    defaultToneMapper: 'drago',

    // ── default uniforms ─────────────────────────────────────────────────
    // Three of these (pivot, contrast, saturation) are driven by the
    // global floating-nav sliders and apply identically to every loaded
    // panel. 'exposure' is per-panel and lives in ComparisonSection state.
    //
    // contrast=1.0 is the "neutral" point for the apply_contrast helper
    // every mapper uses; the slider sweeps symmetrically around it.
    toneMapperParams: {
      exposure:   1.0,
      pivot:      0.5,
      contrast:   1.0,
      saturation: 1.0,
    },

    // ── Method dropdown ordering ─────────────────────────────────────────
    // Methods listed here appear first (in this order) in each panel's
    // method <select>; anything else falls through to alphabetical.
    methodOrder: ['Input', 'GT', 'Ours', 'LumiVid', 'HDRCNN', 'LEDiff'],

    // Display-name overrides for the method dropdown. The underlying value
    // stays the canonical method name (used in file paths and lock checks).
    // We only override the visible text. Currently used to flag the SDR
    // input clearly: "Input" → "Input (SDR)".
    methodDisplayNames: {
      'Input': 'Input (SDR)',
    },

    // Preferred initial selection per panel side: panel 0 (left) prefers
    // 'Input', panel 1 (right) prefers 'Ours'. Falls back to first two
    // entries of `methodOrder` if these aren't available for the scene.
    initialPanelMethods: ['Input', 'Ours'],

    // Dataset names that should be displayed in all caps (acronyms). Other
    // names get title-case (first letter upper, rest as-is). Add new
    // acronyms here as datasets are introduced.
    datasetAcronyms: new Set(['ubc', 'mit', 'nyu', 'kth']),

    // ── Cinema scene titles ──────────────────────────────────────────────
    // Maps exact scene names in the cinema section to their human-readable
    // film credit. Shown as a label beneath the panel-grid.
    cinemaSceneTitles: {
      "ghostbusters1_1280x704_17frames_from_114s":       "Ghostbusters (2016) · Sony Pictures",
      "spiderman2_1280x704_17frames_stride2_from_48s":   "Spider-Man (2002) · Sony Pictures",
      "karatekid2_1280x704_17frames_stride2_from_466s":  "The Karate Kid (2010) · Sony Pictures",
      "spiderman3_1280x704_17frames_stride2_from_298s":  "Spider-Man (2002) · Sony Pictures",
      "backtofuture_1280x704_17frames_from_50s":         "Back to the Future (1985) · Robert Zemeckis",
      "jumanji1_1280x704_17frames_stride2_from_0p1s":    "Jumanji: The Next Level (2019) · Sony Pictures",
      "spiderman2_1280x704_17frames_stride2_from_50s":   "Spider-Man (2002) · Sony Pictures",
      "karatekid1_1280x704_17frames_stride2_from_100s":  "The Karate Kid (1984) · Sony Pictures",
      "spiderman2_1280x704_17frames_stride2_from_33s":   "Spider-Man (2002) · Sony Pictures",
      "ghostbusters1_1280x704_17frames_from_155s":       "Ghostbusters (2016) · Sony Pictures",
      "jumanji1_1280x704_17frames_stride2_from_89p1s":   "Jumanji: The Next Level (2019) · Sony Pictures",
      "karatekid1_1280x704_17frames_stride2_from_24s":   "The Karate Kid (1984) · Sony Pictures",
      "karatekid1_1280x704_17frames_stride2_from_45s":   "The Karate Kid (1984) · Sony Pictures",
      "mib_1280x704_17frames_from_42s":                  "Men in Black (1997) · Sony Pictures",
    },

    // ── Per-section overrides ────────────────────────────────────────────
    // Each section can override the global fps and pin specific scenes to
    // the front of the thumbnail rail. Scenes not listed here fall through
    // alphabetically after the pinned ones.
    sections: {
      wild: {
        fps: 10,
        sceneOrder: [
          "IMG_8763_1280x704_17frames_from_1s",
          "14883069_3840_2160_24fps",
          "IMG_4224_1280x704_17frames_from_1s",
          // "9737883-uhd_3840_2160_24fps", // limitation
          "IMG_4251_1280x704_17frames_from_1s",
          "18898292-uhd_3840_2160_30fps",
          "20240516_164311",
          "20143554-uhd_3840_2160_24fps",
          "IMG_5313_1280x704_17frames_from_1s",
          "IMG_6032_1280x704_17frames_from_1s",
          "20143554-uhd_3840_2160_24fps",
          "IMG_0109_1280x704_17frames_from_1s",
          "14983682_3840_2160_30fps",
          "IMG_4245_1280x704_17frames_from_1s",
          "IMG_3310_1280x704_17frames_from_1s",
          "VID_20210625_174953736",
          "7983982-hd_1920_1080_25fps",
          "VID_20251221_202450262",
          "VID_20260131_171026512",
          "IMG_5591_1280x704_17frames_from_1s",
          "20250820_165537",
          "15820894_1920_1080_30fps",
          "IMG_8750_1280x704_17frames_from_1s",
          "coverr-albino-reindeer-886-1080p",
          "12369387_3840_2160_24fps",
          "coverr-cheering-crowd-1136-1080p",
          "12869656_3840_2160_25fps",
          "VID_20260116_223002240",
          "20250523_172032",
          "coverr-sparks-from-a-bonfire-3727-1080p",
          "coverr-sunlight-shining-through-green-leaves-3256-1080p",
          "tokyo_1280x704_17frames_from_0s",
          "coverr-friends-playing-on-the-beach-8962-1080p",
          "VID_20260307_213515484",
          "VID_20260219_133158069",
          "20221022_231855",
          "15461946-hd_1920_1080_24fps",
          "VID_20260131_164227538",
          "IMG_2349_1280x704_17frames_from_1s",
          "VID_20251221_202045234",
          "VID_20251221_185536544",
          "20250905_121349",
          "irwin",
          "12737869_3840_2160_24fps",
          "20220108_171246",
          "20220714_134928",
          "IMG_4817_1280x704_17frames_from_1s",
          "20221112_112549",
          "20250802_211857",
          "20240516_173013",
          "20251015_070811",
          "20251016_164706",
          "20240519_112818",
          "20251202_134029",
          "20251116_025034",
          "20250819_140728",
          "20240522_113526",
          "8775877-uhd_3840_2160_25fps",
          "20240523_090425",
          "20240518_172636",
          "VID_20260306_160156523",
          "20241008_153547",
          // "5379003-uhd_4096_2160_25fps",
          "20250528_205037",
          "9564079-uhd_4096_2160_25fps",
          "coverr-view-of-a-shopping-mall-1583-1080p",
        ],
      },
      cinema: {
        fps: 10,
        sceneOrder: [
          "ghostbusters1_1280x704_17frames_from_114s",
          "spiderman2_1280x704_17frames_stride2_from_48s",
          "karatekid2_1280x704_17frames_stride2_from_466s",
          "spiderman3_1280x704_17frames_stride2_from_298s",
          "backtofuture_1280x704_17frames_from_50s",
          "jumanji1_1280x704_17frames_stride2_from_0p1s",
          "spiderman2_1280x704_17frames_stride2_from_50s",
          "karatekid1_1280x704_17frames_stride2_from_100s",
          "spiderman2_1280x704_17frames_stride2_from_33s",
          "ghostbusters1_1280x704_17frames_from_155s",
          "jumanji1_1280x704_17frames_stride2_from_89p1s",
          "karatekid1_1280x704_17frames_stride2_from_24s",
          "karatekid1_1280x704_17frames_stride2_from_45s",
          "mib_1280x704_17frames_from_42s",
        ],
      },
      text_to_video: {
        fps: 10,
        sceneOrder: [
          'A_cyclist_riding_along_a_coastal_road_at_midday',
          'A_garden_at_night_with_no_exterior_lighting',
          'A_boat_wake_spreading_across_calm_water_in_full_sun',
          'A_golden_retriever_running_through_a_sunlit_park_in_slow_motion',
          'A_hallway_in_an_old_hotel_with_most_lights_off',
          'A_child_playing_in_a_sprinkler_on_a_sunny_lawn',
          'A_nighttime_aerial_shot_of_farmland_far_from_any_city_lights',
          'A_river_rapids_sequence_in_bright_midday_light',
          'A_mountain_goat_standing_on_a_rocky_ridge_against_a_bright_sky',
          'Waves_crashing_on_a_white_sand_beach_at_noon',
          'A_horse_standing_in_an_unlit_stable_at_night',
          'A_wedding_ceremony_in_an_outdoor_garden_at_midday',
          'A_campfire_burning_on_a_bright_sunny_day_outdoors',
          'A_factory_floor_with_sparks_flying_from_a_welding_station',
          'A_subway_car_interior_late_at_night_with_most_lights_off',
          'A_night_market_filmed_from_a_distance_with_poor_light_reach',
          'A_deer_grazing_in_a_meadow_at_predawn_with_no_sunrise_color_yet',
          'A_woman_walking_through_a_flower_field_in_summer',
          'A_flock_of_white_sheep_grazing_on_a_hillside_in_afternoon_sun',
          'A_river_at_night_with_moonlight_blocked_by_clouds',
          'A_city_street_during_a_total_blackout_at_night',
          'A_small_fishing_boat_on_a_dark_sea_before_dawn',
          'An_abandoned_building_interior_filmed_at_night',
          'A_market_fish_stall_with_ice_and_fresh_catches_on_a_sunny_day',
          'A_slow-motion_close-up_of_a_dandelion_releasing_seeds_in_a_breeze',
          'A_motorbike_on_a_salt_flat_under_a_blazing_midday_sun',
          'A_park_fountain_at_midnight_with_no_path_lighting',
          'A_scuba_diver_exploring_a_shipwreck_at_depth_in_low_visibility',
          'A_skateboarder_performing_tricks_in_a_concrete_plaza_at_midday',
          'A_sports_car_accelerating_on_a_sunlit_highway',

          'A_coastal_cliff_top_with_crashing_waves_viewed_against_a_bright_sky',
          'A_barn_owl_hunting_over_a_dark_field_at_night',
          'A_greenhouse_interior_with_sunlight_streaming_through_glass_panels',
          'A_barista_pouring_latte_art_in_a_bright_cafe',
          'A_close-up_of_soap_bubbles_floating_in_bright_sunlight',
          'A_row_of_sailboats_rocking_in_a_harbor_on_a_sunny_day',
          'A_crow_perched_on_a_dark_fence_post_at_dusk_under_heavy_cloud_cover',
          'A_musician_playing_guitar_in_a_dark_corner_of_a_bar_with_no_spotlight',
          'A_hummingbird_hovering_near_bright_red_flowers_in_sunlight',
          'A_swan_gliding_on_a_reflective_lake_surface_in_morning_sun',
          'A_kitchen_at_night_with_all_lights_off_and_minimal_moonlight_through_a_window',
          'A_medical_professional_in_a_white_coat_under_bright_clinical_lighting',
          'A_warehouse_interior_at_night_filmed_without_any_active_lighting',
          'A_lone_wolf_walking_across_a_field_under_a_cloudy_moonless_night',
          'A_puppy_sitting_on_dark_grass_at_night_under_a_single_dim_streetlight',
          'A_swimmer_doing_laps_in_an_outdoor_pool_on_a_sunny_day',
          'A_race_car_pit_stop_under_stadium_floodlights',
          'A_rainy_night_street_filmed_from_inside_a_dark_building',
          'A_slow_zoom_into_a_white_marble_statue_in_direct_sunlight',
          'A_sleeping_lion_in_the_shade_of_a_tree_at_dusk',
          'A_tennis_player_serving_on_an_outdoor_court_in_direct_sunlight',
          'A_slow-motion_waterfall_in_a_deeply_shaded_forest_canyon',
          'A_slow_pan_across_a_snowy_mountain_range_in_bright_sunlight',
          'A_subway_platform_between_trains_with_minimal_emergency_lighting',
          'A_sun-drenched_terrace_cafe_with_white_tablecloths_and_parasols',
          'A_train_arriving_at_a_station_emerging_from_a_dark_tunnel_into_full_daylight',
          'An_old_lighthouse_interior_at_night_with_no_working_lamp',
          'An_underwater_cave_system_with_minimal_bioluminescence',

        ],
      },
      datasets: {
        fps: 24,
        sceneOrder: [
          // e.g. 'Hallway', 'bistro_01',
        ],
      },
      limitations: {
        fps: 10,
        sceneOrder: [
          'output_1280x704_17frames_from_1s',
          '9737883-uhd_3840_2160_24fps',
          'over_carousel_fireworks_02',
          '20230416_130120',
          'A_flock_of_white_seagulls_flying_over_a_bright_ocean',
          'A_candlelit_dinner_table_filmed_in_near_darkness',
          'A_car_wash_tunnel_with_jets_of_soapy_water_lit_from_above',
          'A_person_walking_through_a_forest_at_dusk',

        ],
      },
    },
  };

  /* ── Display-name helper ────────────────────────────────────────────── */

  /** Convert a canonical method name to its UI-visible label.
   *  Pure presentation — callers should still use the canonical name for
   *  file paths, lock checks, and config keys. */
  function methodDisplayName(method) {
    if (method == null) return '';
    const map = CONFIG.methodDisplayNames || {};
    return map[method] || method;
  }

  /** Convert a dataset name to its UI-visible label. Acronyms get fully
   *  capitalized (UBC, MIT, …); everything else gets title-case. */
  function datasetDisplayName(ds) {
    if (!ds) return '';
    if (CONFIG.datasetAcronyms && CONFIG.datasetAcronyms.has(ds.toLowerCase())) {
      return ds.toUpperCase();
    }
    return ds.charAt(0).toUpperCase() + ds.slice(1);
  }

  /* ── Per-section helpers ────────────────────────────────────────────── */

  /** FPS the named section wants on entry (falls back to CONFIG.fps). */
  function sectionFps(sectionId) {
    const s = CONFIG.sections && CONFIG.sections[sectionId];
    return (s && Number.isFinite(s.fps)) ? s.fps : CONFIG.fps;
  }

  /**
   * Order an array of scene names for the given section: scenes in the
   * section's sceneOrder come first in that exact order; remaining scenes
   * are appended sorted alphabetically. Missing scenes in the hot-list
   * (scenes the manifest doesn't have for the current dataset+exposure)
   * are skipped silently.
   */
  function orderScenes(sectionId, scenes) {
    const s = CONFIG.sections && CONFIG.sections[sectionId];
    const hot = (s && Array.isArray(s.sceneOrder)) ? s.sceneOrder : [];
    const set = new Set(scenes);
    const head = hot.filter(n => set.has(n));
    const headSet = new Set(head);
    const tail = scenes.filter(n => !headSet.has(n)).sort();
    return [...head, ...tail];
  }

  /**
   * Convert a text-to-video scene name into a human-readable prompt.
   * The wild-outputs script normalises filenames like
   *   'A_barista_pouring_latte_art_in_a_bright_cafe'
   * which were the original WAN prompts with spaces → underscores.
   * Just reverse that.
   */
  function promptFromSceneName(sceneName) {
    if (!sceneName) return '';
    return sceneName.replace(/_/g, ' ').trim();
  }

  /**
   * Resolve a video for (dataset, exposure, scene, method) into a source
   * object: { url: string|null, dispose: ()=>void, error?: string }
   *
   * Standard path:  {dataset}/{exposure}/{scene}/method_{method}.mp4
   * GT special:     {dataset}/gt/{scene}/method_GT.mp4 — the ground-truth
   *   video is stored once per (dataset, scene) regardless of which input
   *   exposure tab the user is viewing.
   *
   * If the user has picked the videos folder via the picker, we create a
   * same-origin blob: URL from the cached File object. Otherwise we fall
   * back to a relative path (works on Safari file://, http servers, and
   * Chrome with --allow-file-access-from-files).
   */
  function videoSource(dataset, exposure, scene, method) {
    const effectiveExposure = (method === 'GT') ? 'gt' : exposure;
    const rel = `${dataset}/${effectiveExposure}/${scene}/method_${method}.mp4`;
    const fs  = window.App.fileSource;
    if (fs && fs.hasAny()) {
      const url = fs.makeBlobUrl(rel);
      if (url) return { url, dispose: () => fs.revoke(url) };
      return { url: null, dispose: () => {},
               error: `'${rel}' was not found in the selected videos folder.` };
    }
    return { url: `./videos/${rel}`, dispose: () => {} };
  }

  /** Resolve a precomputed thumbnail for (dataset, exposure, scene). */
  function thumbnailSource(dataset, exposure, scene) {
    const rel = `thumbnails/${dataset}/${exposure}/${scene}.jpg`;
    const fs  = window.App.fileSource;
    if (fs && fs.hasAny()) {
      const url = fs.makeBlobUrl(rel);
      if (url) return { url };
      return { url: null };  // not precomputed; fall back to JS decode
    }
    return { url: `./videos/${rel}` };
  }

  /**
   * Load manifest.json from the picked folder if available, else from the
   * relative ./videos/ path. Returns the parsed object on success, or null
   * on failure (caller decides what to do — typically show the picker).
   *
   * Safari note: Safari treats file:// pages as same-origin with sibling
   * file:// resources, so the fetch usually succeeds without a picker.
   * But some Safari configurations (e.g. private-browsing + cached file
   * handles, or a stricter security profile) return HTTP 0 here. We can't
   * distinguish "missing file" from "blocked by browser" — both surface
   * as a thrown TypeError / HTTP 0. Caller treats null as a signal to fall
   * back to the picker.
   */
  async function loadManifest() {
    const fs = window.App.fileSource;
    if (fs && fs.hasAny()) {
      const url = fs.makeBlobUrl('manifest.json');
      if (url) {
        try {
          const resp = await fetch(url);
          const data = await resp.json();
          fs.revoke(url);
          return data;
        } catch (e) {
          console.warn('Could not load manifest from folder picker:', e);
        }
      }
    }
    try {
      const resp = await fetch('./videos/manifest.json');
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
      return await resp.json();
    } catch (e) {
      console.warn('Could not fetch ./videos/manifest.json:', e);
      return null;
    }
  }

  return {
    CONFIG,
    videoSource,
    thumbnailSource,
    loadManifest,
    sectionFps,
    orderScenes,
    promptFromSceneName,
    methodDisplayName,
    datasetDisplayName,
  };
})();
